import { Operation } from "./types";

export const rawData: Operation[] = [
  {
    id: "12BPM/5019/2026",
    date: "16/03/2026",
    time: "01:30",
    uope: "12º BPM",
    location: "[ Palmeira ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BOPE/5018/2026",
    date: "17/03/2026",
    time: "05:00",
    uope: "BOPE",
    location: "[ PRAZERES E ESCONDIDINHO INCOMPLETO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "17BPM/5017/2026",
    date: "17/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ Barbante/Joaniza ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "18BPM/4998/2026",
    date: "13/03/2026",
    time: "12:09",
    uope: "18º BPM",
    location: "[ Bateau Mouche ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "18BPM/5009/2026",
    date: "16/03/2026",
    time: "06:41",
    uope: "18º BPM",
    location: "[ Bateau Mouche ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BAC/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "BAC",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BAC/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "BAC",
    location: "[ NOVA HOLANDA ] - [ PARQUE UNIÃO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/5010/2026",
    date: "13/03/2026",
    time: "07:35",
    uope: "9º BPM",
    location: "[ Fubá ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/5010/2026",
    date: "13/03/2026",
    time: "07:35",
    uope: "9º BPM",
    location: "[ Fubá ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "18BPM/5009/2026",
    date: "16/03/2026",
    time: "06:41",
    uope: "18º BPM",
    location: "[ Bateau Mouche ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BOPE/5005/2026",
    date: "15/03/2026",
    time: "23:30",
    uope: "BOPE",
    location: "[ Complexo do Chapadão ]",
    circumstance: "Emergencial",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "18BPM/5006/2026",
    date: "16/03/2026",
    time: "05:00",
    uope: "18º BPM",
    location: "[ Chapadão ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BOPE/5003/2026",
    date: "15/03/2026",
    time: "00:30",
    uope: "BOPE",
    location: "[ Complexo do Chapadão ]",
    circumstance: "Emergencial",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "7BPM/4994/2026",
    date: "13/03/2026",
    time: "13:00",
    uope: "7º BPM",
    location: "[ Jardim Catarina Novo ] - [ Jardim Catarina Velho ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BOPE/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "BOPE",
    location: "[ NOVA HOLANDA ] - [ Nova Holanda ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "18BPM/4995/2026",
    date: "13/03/2026",
    time: "03:44",
    uope: "18º BPM",
    location: "[ Jordão ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "7BPM/4994/2026",
    date: "13/03/2026",
    time: "13:00",
    uope: "7º BPM",
    location: "[ Jardim Catarina Novo ] - [ Jardim Catarina Velho ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Finalizado"
  },
  {
    id: "17BPM/4978/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ COMPLEXO DO DENDÊ ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BPCHQ/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "BPCHQ",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "20BPM/4986/2026",
    date: "12/03/2026",
    time: "06:00",
    uope: "20º BPM",
    location: "[ Grão Pará ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BPCHQ/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "BPCHQ",
    location: "[ NOVA HOLANDA ] - [ PARQUE UNIÃO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "GAM/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "GAM",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BOPE/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "BOPE",
    location: "[ Cidade de Deus ] - [ Vila Sapê ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "35BPM/4982/2026",
    date: "11/03/2026",
    time: "11:00",
    uope: "35º BPM",
    location: "[ COMPLEXO DA RETA ]",
    circumstance: "Emergencial",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "COE/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "COE",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "GAM/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "GAM",
    location: "[ NOVA HOLANDA ] - [ PARQUE UNIÃO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BOPE/4964/2026",
    date: "10/03/2026",
    time: "13:20",
    uope: "BOPE",
    location: "[ ARARÁ (ARARÁ/MANDELA) ]",
    circumstance: "Emergencial",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BOPE/4946/2026",
    date: "08/03/2026",
    time: "20:30",
    uope: "BOPE",
    location: "[ ANDARAÍ ]",
    circumstance: "Emergencial",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "17BPM/4978/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ COMPLEXO DO DENDÊ ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BAC/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "BAC",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BPCHQ/4973/2026",
    date: "11/03/2026",
    time: "05:00",
    uope: "BPCHQ",
    location: "[ Cidade de Deus ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "17BPM/4958/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ COMPLEXO DO DENDÊ ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Enviado",
    status: "Finalizado"
  },
  {
    id: "17BPM/4958/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ COMPLEXO DO DENDÊ ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "COE/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "COE",
    location: "[ NOVA HOLANDA ] - [ PARQUE UNIÃO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/4966/2026",
    date: "09/03/2026",
    time: "09:34",
    uope: "9º BPM",
    location: "[ Campinho ] - [ Fubá ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/4966/2026",
    date: "09/03/2026",
    time: "09:34",
    uope: "9º BPM",
    location: "[ Campinho ] - [ Fubá ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "BAC/4929/2026",
    date: "06/03/2026",
    time: "05:00",
    uope: "BAC",
    location: "[ Morro do 18 ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "BPCHQ/4959/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "BPCHQ",
    location: "[ NOVA HOLANDA ] - [ PARQUE UNIÃO ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "17BPM/4958/2026",
    date: "10/03/2026",
    time: "05:00",
    uope: "17º BPM",
    location: "[ COMPLEXO DO DENDÊ ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  },
  {
    id: "9BPM/4951/2026",
    date: "06/03/2026",
    time: "10:51",
    uope: "9º BPM",
    location: "[ Campinho ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/4951/2026",
    date: "06/03/2026",
    time: "11:51",
    uope: "9º BPM",
    location: "[ Campinho ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Enviado",
    status: "Finalizado"
  },
  {
    id: "GAM/4929/2026",
    date: "06/03/2026",
    time: "05:00",
    uope: "GAM",
    location: "[ Morro do 18 ]",
    circumstance: "Planejada",
    initialCommunication: "Enviado",
    finalReport: "Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/4951/2026",
    date: "06/03/2026",
    time: "11:51",
    uope: "9º BPM",
    location: "[ Campinho ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Enviado",
    status: "Finalizado"
  },
  {
    id: "9BPM/4951/2026",
    date: "06/03/2026",
    time: "11:51",
    uope: "9º BPM",
    location: "[ Campinho ]",
    circumstance: "Ocorrência Policial em Área Sensível",
    initialCommunication: "Enviado",
    finalReport: "Não Iniciado",
    status: "Em andamento"
  }
];
